import type { AdminPermission } from "@/lib/admin/permissions";

export type HttpMethod = "GET" | "POST" | "PATCH" | "PUT" | "DELETE";

export type AdminModuleEndpoint = {
  /** Unique id for test titles */
  id: string;
  /** Module group label */
  module: string;
  method: HttpMethod;
  /** Absolute path used in Request URL (params filled) */
  path: string;
  /** Primary permission checked first by the handler */
  permission: AdminPermission;
  /** Import path relative to project `@/` alias without extension */
  importPath: string;
  /** Optional JSON body for mutating methods */
  body?: unknown;
  /** Skip allowed-role call (handler needs heavy DB / file IO) — still test 401/403 */
  skipAllowedProbe?: boolean;
};

/**
 * Declarative catalog of gated admin API endpoints.
 * Auth route is intentionally excluded.
 */
export const ADMIN_API_CATALOG: AdminModuleEndpoint[] = [
  // Core
  {
    id: "dashboard.GET",
    module: "dashboard",
    method: "GET",
    path: "/api/admin/dashboard",
    permission: "dashboard.view",
    importPath: "@/app/api/admin/dashboard/route",
  },

  // Products
  {
    id: "products.GET",
    module: "products",
    method: "GET",
    path: "/api/admin/products",
    permission: "products.view",
    importPath: "@/app/api/admin/products/route",
  },
  {
    id: "products.POST",
    module: "products",
    method: "POST",
    path: "/api/admin/products",
    permission: "products.create",
    importPath: "@/app/api/admin/products/route",
    body: { title: "t" },
    skipAllowedProbe: true,
  },
  {
    id: "products.id.GET",
    module: "products",
    method: "GET",
    path: "/api/admin/products/p1",
    permission: "products.view",
    importPath: "@/app/api/admin/products/[id]/route",
  },
  {
    id: "products.id.PATCH",
    module: "products",
    method: "PATCH",
    path: "/api/admin/products/p1",
    permission: "products.edit",
    importPath: "@/app/api/admin/products/[id]/route",
    body: { title: "x" },
    skipAllowedProbe: true,
  },
  {
    id: "products.id.DELETE",
    module: "products",
    method: "DELETE",
    path: "/api/admin/products/p1",
    permission: "products.delete",
    importPath: "@/app/api/admin/products/[id]/route",
    skipAllowedProbe: true,
  },
  {
    id: "products.bulk.POST",
    module: "products",
    method: "POST",
    path: "/api/admin/products/bulk",
    permission: "products.bulk",
    importPath: "@/app/api/admin/products/bulk/route",
    body: { ids: [], action: "archive" },
    skipAllowedProbe: true,
  },
  {
    id: "products.export.GET",
    module: "products",
    method: "GET",
    path: "/api/admin/products/export",
    permission: "products.import_export",
    importPath: "@/app/api/admin/products/export/route",
  },
  {
    id: "products.import.POST",
    module: "products",
    method: "POST",
    path: "/api/admin/products/import",
    permission: "products.import_export",
    importPath: "@/app/api/admin/products/import/route",
    body: { rows: [] },
    skipAllowedProbe: true,
  },
  {
    id: "products.revisions.GET",
    module: "products",
    method: "GET",
    path: "/api/admin/products/p1/revisions",
    permission: "products.view",
    importPath: "@/app/api/admin/products/[id]/revisions/route",
  },
  {
    id: "products.restore.POST",
    module: "products",
    method: "POST",
    path: "/api/admin/products/p1/restore",
    permission: "products.delete",
    importPath: "@/app/api/admin/products/[id]/restore/route",
    skipAllowedProbe: true,
  },
  {
    id: "product-fields.GET",
    module: "product-fields",
    method: "GET",
    path: "/api/admin/product-fields",
    permission: "products.view",
    importPath: "@/app/api/admin/product-fields/route",
  },
  {
    id: "product-fields.POST",
    module: "product-fields",
    method: "POST",
    path: "/api/admin/product-fields",
    permission: "products.manage_fields",
    importPath: "@/app/api/admin/product-fields/route",
    body: {},
    skipAllowedProbe: true,
  },

  // Categories / brands / inventory
  {
    id: "categories.GET",
    module: "categories",
    method: "GET",
    path: "/api/admin/categories",
    permission: "categories.view",
    importPath: "@/app/api/admin/categories/route",
  },
  {
    id: "categories.POST",
    module: "categories",
    method: "POST",
    path: "/api/admin/categories",
    permission: "categories.manage",
    importPath: "@/app/api/admin/categories/route",
    body: { name: "x", slug: "x" },
    skipAllowedProbe: true,
  },
  {
    id: "brands.GET",
    module: "brands",
    method: "GET",
    path: "/api/admin/brands",
    permission: "brands.view",
    importPath: "@/app/api/admin/brands/route",
  },
  {
    id: "brands.POST",
    module: "brands",
    method: "POST",
    path: "/api/admin/brands",
    permission: "brands.manage",
    importPath: "@/app/api/admin/brands/route",
    body: { name: "b", slug: "b" },
    skipAllowedProbe: true,
  },
  {
    id: "inventory.GET",
    module: "inventory",
    method: "GET",
    path: "/api/admin/inventory",
    permission: "inventory.view",
    importPath: "@/app/api/admin/inventory/route",
  },
  {
    id: "inventory.PATCH",
    module: "inventory",
    method: "PATCH",
    path: "/api/admin/inventory",
    permission: "inventory.edit",
    importPath: "@/app/api/admin/inventory/route",
    body: { productId: "p1", inStock: true },
    skipAllowedProbe: true,
  },

  // Sellers
  {
    id: "sellers.GET",
    module: "sellers",
    method: "GET",
    path: "/api/admin/sellers",
    permission: "sellers.view",
    importPath: "@/app/api/admin/sellers/route",
  },
  {
    id: "sellers.POST",
    module: "sellers",
    method: "POST",
    path: "/api/admin/sellers",
    permission: "sellers.manage",
    importPath: "@/app/api/admin/sellers/route",
    body: {},
    skipAllowedProbe: true,
  },
  {
    id: "sellers.id.GET",
    module: "sellers",
    method: "GET",
    path: "/api/admin/sellers/s1",
    permission: "sellers.view",
    importPath: "@/app/api/admin/sellers/[id]/route",
  },
  {
    id: "sellers.id.PATCH",
    module: "sellers",
    method: "PATCH",
    path: "/api/admin/sellers/s1",
    permission: "sellers.manage",
    importPath: "@/app/api/admin/sellers/[id]/route",
    body: { status: "active" },
    skipAllowedProbe: true,
  },
  {
    id: "sellers.withdrawals.GET",
    module: "sellers",
    method: "GET",
    path: "/api/admin/sellers/s1/withdrawals",
    permission: "sellers.manage",
    importPath: "@/app/api/admin/sellers/[id]/withdrawals/route",
  },
  {
    id: "sellers.withdrawals.PATCH",
    module: "sellers",
    method: "PATCH",
    path: "/api/admin/sellers/s1/withdrawals",
    permission: "sellers.manage",
    importPath: "@/app/api/admin/sellers/[id]/withdrawals/route",
    body: { withdrawalId: "w1", status: "approved" },
    skipAllowedProbe: true,
  },
  {
    id: "seller-products.PATCH",
    module: "sellers",
    method: "PATCH",
    path: "/api/admin/seller-products/p1",
    permission: "sellers.manage",
    importPath: "@/app/api/admin/seller-products/[id]/route",
    body: { approvalStatus: "approved" },
    skipAllowedProbe: true,
  },

  // Orders / customers / coupons
  {
    id: "orders.GET",
    module: "orders",
    method: "GET",
    path: "/api/admin/orders",
    permission: "orders.view",
    importPath: "@/app/api/admin/orders/route",
  },
  {
    id: "orders.PATCH",
    module: "orders",
    method: "PATCH",
    path: "/api/admin/orders",
    permission: "orders.edit",
    importPath: "@/app/api/admin/orders/route",
    body: { orderId: "o1", status: "confirmed" },
    skipAllowedProbe: true,
  },
  {
    id: "orders.id.GET",
    module: "orders",
    method: "GET",
    path: "/api/admin/orders/o1",
    permission: "orders.view",
    importPath: "@/app/api/admin/orders/[id]/route",
  },
  {
    id: "orders.id.PATCH",
    module: "orders",
    method: "PATCH",
    path: "/api/admin/orders/o1",
    permission: "orders.edit",
    importPath: "@/app/api/admin/orders/[id]/route",
    body: { status: "confirmed" },
    skipAllowedProbe: true,
  },
  {
    id: "orders.export.GET",
    module: "orders",
    method: "GET",
    path: "/api/admin/orders/export",
    permission: "reports.export",
    importPath: "@/app/api/admin/orders/export/route",
  },
  {
    id: "customers.GET",
    module: "customers",
    method: "GET",
    path: "/api/admin/customers",
    permission: "customers.view",
    importPath: "@/app/api/admin/customers/route",
  },
  {
    id: "customers.id.GET",
    module: "customers",
    method: "GET",
    path: "/api/admin/customers/c1",
    permission: "customers.view",
    importPath: "@/app/api/admin/customers/[id]/route",
  },
  {
    id: "customers.id.POST",
    module: "customers",
    method: "POST",
    path: "/api/admin/customers/c1",
    permission: "customers.edit",
    importPath: "@/app/api/admin/customers/[id]/route",
    body: { action: "note", note: "x" },
    skipAllowedProbe: true,
  },
  {
    id: "customers.export.GET",
    module: "customers",
    method: "GET",
    path: "/api/admin/customers/export",
    permission: "reports.export",
    importPath: "@/app/api/admin/customers/export/route",
  },
  {
    id: "coupons.GET",
    module: "coupons",
    method: "GET",
    path: "/api/admin/coupons",
    permission: "coupons.view",
    importPath: "@/app/api/admin/coupons/route",
  },
  {
    id: "coupons.POST",
    module: "coupons",
    method: "POST",
    path: "/api/admin/coupons",
    permission: "coupons.manage",
    importPath: "@/app/api/admin/coupons/route",
    body: { code: "X", type: "percent", value: 10 },
    skipAllowedProbe: true,
  },

  // Engagement
  {
    id: "reviews.GET",
    module: "reviews",
    method: "GET",
    path: "/api/admin/reviews",
    permission: "reviews.view",
    importPath: "@/app/api/admin/reviews/route",
  },
  {
    id: "reviews.PATCH",
    module: "reviews",
    method: "PATCH",
    path: "/api/admin/reviews",
    permission: "reviews.moderate",
    importPath: "@/app/api/admin/reviews/route",
    body: { id: "r1", status: "approved" },
    skipAllowedProbe: true,
  },
  {
    id: "qa.GET",
    module: "qa",
    method: "GET",
    path: "/api/admin/qa",
    permission: "qa.view",
    importPath: "@/app/api/admin/qa/route",
  },
  {
    id: "qa.PATCH",
    module: "qa",
    method: "PATCH",
    path: "/api/admin/qa",
    permission: "qa.manage",
    importPath: "@/app/api/admin/qa/route",
    body: { id: "q1", answer: "a" },
    skipAllowedProbe: true,
  },
  {
    id: "messages.GET",
    module: "messages",
    method: "GET",
    path: "/api/admin/messages",
    permission: "messages.view",
    importPath: "@/app/api/admin/messages/route",
  },
  {
    id: "messages.PATCH",
    module: "messages",
    method: "PATCH",
    path: "/api/admin/messages",
    permission: "messages.manage",
    importPath: "@/app/api/admin/messages/route",
    body: { id: "m1", read: true },
    skipAllowedProbe: true,
  },
  {
    id: "tickets.GET",
    module: "tickets",
    method: "GET",
    path: "/api/admin/tickets",
    permission: "tickets.view",
    importPath: "@/app/api/admin/tickets/route",
  },
  {
    id: "tickets.POST",
    module: "tickets",
    method: "POST",
    path: "/api/admin/tickets",
    permission: "tickets.manage",
    importPath: "@/app/api/admin/tickets/route",
    body: { subject: "s" },
    skipAllowedProbe: true,
  },
  {
    id: "newsletter.GET",
    module: "newsletter",
    method: "GET",
    path: "/api/admin/newsletter",
    permission: "newsletter.view",
    importPath: "@/app/api/admin/newsletter/route",
  },

  // CMS
  {
    id: "articles.GET",
    module: "articles",
    method: "GET",
    path: "/api/admin/articles",
    permission: "articles.view",
    importPath: "@/app/api/admin/articles/route",
  },
  {
    id: "articles.POST",
    module: "articles",
    method: "POST",
    path: "/api/admin/articles",
    permission: "articles.manage",
    importPath: "@/app/api/admin/articles/route",
    body: { title: "a", slug: "a" },
    skipAllowedProbe: true,
  },
  {
    id: "pages.GET",
    module: "pages",
    method: "GET",
    path: "/api/admin/pages",
    permission: "pages.view",
    importPath: "@/app/api/admin/pages/route",
  },
  {
    id: "pages.POST",
    module: "pages",
    method: "POST",
    path: "/api/admin/pages",
    permission: "pages.manage",
    importPath: "@/app/api/admin/pages/route",
    body: { title: "p", slug: "p" },
    skipAllowedProbe: true,
  },
  {
    id: "banners.GET",
    module: "banners",
    method: "GET",
    path: "/api/admin/banners",
    permission: "banners.view",
    importPath: "@/app/api/admin/banners/route",
  },
  {
    id: "banners.POST",
    module: "banners",
    method: "POST",
    path: "/api/admin/banners",
    permission: "banners.manage",
    importPath: "@/app/api/admin/banners/route",
    body: { title: "b" },
    skipAllowedProbe: true,
  },
  {
    id: "media.GET",
    module: "media",
    method: "GET",
    path: "/api/admin/media",
    permission: "media.view",
    importPath: "@/app/api/admin/media/route",
  },
  {
    id: "media.POST",
    module: "media",
    method: "POST",
    path: "/api/admin/media",
    permission: "media.manage",
    importPath: "@/app/api/admin/media/route",
    body: { filename: "x.jpg", url: "/x.jpg", mimeType: "image/jpeg", sizeBytes: 1, originalName: "x.jpg" },
    skipAllowedProbe: true,
  },
  {
    id: "content.GET",
    module: "content",
    method: "GET",
    path: "/api/admin/content",
    permission: "content.view",
    importPath: "@/app/api/admin/content/route",
  },
  {
    id: "content.PATCH",
    module: "content",
    method: "PATCH",
    path: "/api/admin/content",
    permission: "content.manage",
    importPath: "@/app/api/admin/content/route",
    body: { hero: { title: "t" } },
    skipAllowedProbe: true,
  },

  // System
  {
    id: "notifications.GET",
    module: "notifications",
    method: "GET",
    path: "/api/admin/notifications",
    permission: "notifications.view",
    importPath: "@/app/api/admin/notifications/route",
  },
  {
    id: "notifications.POST",
    module: "notifications",
    method: "POST",
    path: "/api/admin/notifications",
    permission: "notifications.manage",
    importPath: "@/app/api/admin/notifications/route",
    body: { title: "n", body: "b" },
    skipAllowedProbe: true,
  },
  {
    id: "reports.GET",
    module: "reports",
    method: "GET",
    path: "/api/admin/reports",
    permission: "reports.view",
    importPath: "@/app/api/admin/reports/route",
  },
  {
    id: "logs.GET",
    module: "logs",
    method: "GET",
    path: "/api/admin/logs",
    permission: "logs.view",
    importPath: "@/app/api/admin/logs/route",
  },
  {
    id: "users.GET",
    module: "users",
    method: "GET",
    path: "/api/admin/users",
    permission: "admin_users.view",
    importPath: "@/app/api/admin/users/route",
  },
  {
    id: "users.POST",
    module: "users",
    method: "POST",
    path: "/api/admin/users",
    permission: "admin_users.manage",
    importPath: "@/app/api/admin/users/route",
    body: { fullName: "a", email: "a@b.c", password: "secret12", role: "support" },
    skipAllowedProbe: true,
  },
  {
    id: "settings.GET",
    module: "settings",
    method: "GET",
    path: "/api/admin/settings",
    permission: "settings.view",
    importPath: "@/app/api/admin/settings/route",
  },
  {
    id: "settings.PATCH",
    module: "settings",
    method: "PATCH",
    path: "/api/admin/settings",
    permission: "settings.edit",
    importPath: "@/app/api/admin/settings/route",
    body: { shippingCost: 1000 },
    skipAllowedProbe: true,
  },
];

export const ADMIN_NAV_PATHS = [
  "/admin/dashboard",
  "/admin/products",
  "/admin/product-fields",
  "/admin/categories",
  "/admin/brands",
  "/admin/inventory",
  "/admin/sellers",
  "/admin/orders",
  "/admin/customers",
  "/admin/coupons",
  "/admin/reviews",
  "/admin/qa",
  "/admin/messages",
  "/admin/tickets",
  "/admin/newsletter",
  "/admin/articles",
  "/admin/pages",
  "/admin/banners",
  "/admin/media",
  "/admin/content",
  "/admin/notifications",
  "/admin/reports",
  "/admin/logs",
  "/admin/users",
  "/admin/settings",
] as const;
